name: 'Deploy - Demos'
run-name: ${{ inputs.is_production && '🚀' || '🧪' }} Deploy - Demos

on:
  workflow_dispatch:
    inputs:
      is_production:
        type: boolean
        description: Is production deployment

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      DEPLOY_DIR: ${{ inputs.is_production && secrets.PROD_DIR || secrets.STAG_DIR }}
      TEMPLATE_NAME: sneat-mui-react-nextjs-admin-template

    steps:
      # Checkout current repo
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: ${{ env.TEMPLATE_NAME }}

      # Checkout automation-scripts repo
      - name: Checkout automation-scripts repo
        uses: actions/checkout@v3
        with:
          repository: themeselection/automation-scripts
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: automation-scripts

      # Replace template name in automation-scripts
      - name: Replace template name in automation-scripts
        run: sh generate.sh ${{ env.TEMPLATE_NAME }}
        working-directory: automation-scripts/react/replace-project-name

      # Install packages in typescript full-version
      - name: Install packages in typescript full-version
        run: yarn
        working-directory: ${{ env.TEMPLATE_NAME }}/typescript-version/full-version

      # Generate all the demos
      - name: Generate all the demos
        run: sh generate.sh $([[ "${{ inputs.is_production }}" != "true" ]] && echo staging)
        working-directory: automation-scripts/react/pro/demo-generation

      # Zip demos & delete old demos
      - name: Cleanup demos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            mkdir -p ${{ env.DEPLOY_DIR }}
            cd ${{ env.DEPLOY_DIR }}
            rm -rf demos-backup-*.zip
            DEMO_ZIP_NAME="demos-backup-$(date +"%Y-%m-%d-%H-%M-%S").zip"
            [[ "${{ inputs.is_production }}" == "true" ]] && rm -rf ${{ secrets.STAG_DIR }}/demo-* && zip -r $DEMO_ZIP_NAME demo-*
            rm -rf demo-*

      # Move all demos to github workspace directory
      - name: Move all demos to github workspace directory
        run: mv ${{ env.TEMPLATE_NAME }}/demo-* $GITHUB_WORKSPACE

      # Upload new demos
      - name: Upload new demos
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: demo-1,demo-2,demo-3,demo-4,demo-5,demo-6
          target: ${{ env.DEPLOY_DIR }}
